### ISSUE TITLE
Google Drive Synce Doesn't Upload Files

### ISSUE THREAD

**Issue by SoundsSerious** [SoundsSerious/ottermaticslib#5]
Not sure why, it was looping through them all.

**Comment by SoundsSerious** [comment]
Observed two errors:
[otterlog_OtterDrive     ]''|'Traceback (most recent call last):\n  File "/mnt/c/Users/Sup/Ottermatics Dropbox/Ottermatics/ottermaticslib/ottermatics/gdocs.py", line 221, in search_items\n    all_name_matches = output_version + othermatches\nTypeError: unsupported operand type(s) for +: \'GoogleDriveFile\' and \'list\'\n'
Traceback (most recent call last):
  File "/mnt/c/Users/Sup/Ottermatics Dropbox/Ottermatics/ottermaticslib/ottermatics/gdocs.py", line 221, in search_items
    all_name_matches = output_version + othermatches
TypeError: unsupported operand type(s) for +: 'GoogleDriveFile' and 'list'

fl_carribean_grid_updated_points_843.png
[otterlog_OtterDrive     ]creating 1pCWyp14SIfz2wUc7vupCCsBuulTb6Hf8->/mnt/c/Users/Sup/Ottermatics Dropbox/Projects/Neptunya/media/Archive/fl_carribean_grid_updated_points_844.png
[otterlog_OtterDrive     ]creating 1pCWyp14SIfz2wUc7vupCCsBuulTb6Hf8->/mnt/c/Users/Sup/Ottermatics Dropbox/Projects/Neptunya/media/Archive/fmars-06-00556-g001.jpg
[otterlog_OtterDrive     ]creating 1pCWyp14SIfz2wUc7vupCCsBuulTb6Hf8->/mnt/c/Users/Sup/Ottermatics Dropbox/Projects/Neptunya/media/Archive/gulfstream_grid_updated_points_42.png
[otterlog_OtterDrive     ]'Error Creating File'|'Traceback (most recent call last):\n  File "/mnt/c/Users/Sup/Ottermatics Dropbox/Ottermatics/ottermaticslib/ottermatics/gdocs.py", line 414, in create_file\n    self.add_cached_file(file,gfile_path)\n  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/site-packages/pydrive2/files.py", line 516, in Upload\n    self._FilesInsert(param=param)\n  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/site-packages/pydrive2/auth.py", line 84, in _decorated\n    return decoratee(self, *args, **kwargs)\n  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/site-packages/pydrive2/files.py", line 651, in _FilesInsert\n    raise ApiRequestError(error)\n  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/site-packages/pydrive2/files.py", line 33, in __init__\n    content = json.loads(http_error.content.decode("utf-8"))\n  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/json/__init__.py", line 357, in loads\n    return _default_decoder.decode(s)\n  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/json/decoder.py", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/json/decoder.py", line 355, in raw_decode\n    raise JSONDecodeError("Expecting value", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n'
Traceback (most recent call last):
  File "/mnt/c/Users/Sup/Ottermatics Dropbox/Ottermatics/ottermaticslib/ottermatics/gdocs.py", line 414, in create_file
    self.add_cached_file(file,gfile_path)
  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/site-packages/pydrive2/files.py", line 516, in Upload
    self._FilesInsert(param=param)
  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/site-packages/pydrive2/auth.py", line 84, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/site-packages/pydrive2/files.py", line 651, in _FilesInsert
    raise ApiRequestError(error)
  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/site-packages/pydrive2/files.py", line 33, in __init__
    content = json.loads(http_error.content.decode("utf-8"))
  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/olly/miniconda3/envs/neptunya/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
search: '1pCWyp14SIfz2wUc7vupCCsBuulTb6Hf8' in parents and trashed=false
[otterlog_OtterDrive     ]1YOhAxg-fWwq9d0BdGHoUODkwntZIyYwH - caching directory
